# http://travis-ci.org/#!/ipython/ipywidgets
language: python
python:
    - 3.4
    - 2.7
sudo: false
env:
  matrix:
    - GROUP=python
    - GROUP=js
before_install:
    - 'if [[ $GROUP == js* ]]; then npm install -g casperjs; fi'
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    - pip install -f travis-wheels/wheelhouse file://$PWD#egg=ipywidgets[test] coveralls
script:
    - mkdir /tmp/ipywidgets && cd /tmp/ipywidgets
    - 'if [[ $GROUP == js ]]; then python -m ipywidgets.jstest; fi'
    - 'if [[ $GROUP == python ]]; then nosetests --with-coverage --cover-package=ipywidgets ipywidgets; fi'
matrix:
    include:
        - python: 3.3
          env: GROUP=python

after_success:
    - coveralls
